name: e2e-tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: http://localhost:8080/
          spec: "tests/e2e/**/*"
          config: baseUrl=https://localhost:8080

